--Code to create the SEATING_SECTIONS table.
CREATE TABLE SEATING_SECTIONS (
  SEAT_SECTION_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SECTION_NAME VARCHAR(50) NOT NULL,
  NUMBER_OF_SUBSECTIONS INT(2)
);


--Code to create the SUB_SEATING_SECTIONS table.
CREATE TABLE SUB_SEATING_SECTIONS (
  SUB_SEAT_SECTION_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NUMBER_OF_SEATS INT(4),
  isVIP BOOLEAN,
  SEAT_SECTION_ID INT NOT NULL,
  FOREIGN KEY(SEAT_SECTION_ID) REFERENCES SEATING_SECTIONS(SEAT_SECTION_ID)
);


--Code to create the EVENTS table.
CREATE TABLE EVENTS (
  EVENT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EVENTS_NAME VARCHAR(255),
  TICKETS_SOLD INT(5)
);


--Code to create the SEAT_PRICING_BY_SUB_SECTION table.
CREATE TABLE SEAT_PRICING_BY_SUB_SECTION (
  SEAT_PRICING_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SEAT_PRICE INT(6),
  EVENT_ID INT NOT NULL,
  SUB_SEAT_SECTION_ID INT NOT NULL,
  FOREIGN KEY(EVENT_ID) REFERENCES EVENTS(EVENT_ID),
  FOREIGN KEY(SUB_SEAT_SECTION_ID) REFERENCES SUB_SEATING_SECTIONS(SUB_SEAT_SECTION_ID)
);


--code to create the SEAT_AVAILABILITY_BY_SUB_SECTION table.
CREATE TABLE SEAT_AVAILABILITY_BY_SUB_SECTION (
  SEAT_AVAILABILITY_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SEATS_LEFT INT(5) NOT NULL,
  EVENT_ID INT NOT NULL,
  SUB_SEAT_SECTION_ID INT NOT NULL,
  FOREIGN KEY(EVENT_ID) REFERENCES EVENTS(EVENT_ID),
  FOREIGN KEY(SUB_SEAT_SECTION_ID) REFERENCES SUB_SEATING_SECTIONS(SUB_SEAT_SECTION_ID)
);
